@startuml diagramme-plantuml

skinparam boxPadding 100
skinparam maxMessageSize 300
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250
autonumber

title "Exemple d'un diagramme PlantUML"

Ludovic  -> Public : Comment allez-vous ?

alt Bien

  Public -> Ludovic :  Nous allons bien !

else Pas bien

  Public -> Ludovic :  Nous n'allons pas bien...

end

Ludovic  -> Ludovic : //Écoute la réponse et adapte la présentation si besoin. //
@enduml
